#!/bin/bash

#PBS -q normal
#PBS -N AcademiCodec_test
#PBS -l select=1:ncpus=4:ngpus=4
#PBS -l walltime=00:01:00
#PBS -j oe
#PBS -o ~/AcademiCodec/logs/output.o

echo "AcademiCodec pbs test"
cd $PBS_O_WORKDIR
module load singularity
export SINGULARITY_BIND="/home/project:/home/project,/scratch:/scratch,/app:/app"
singularity run --nv /app/apps/containers/kaldi/kaldi-nvidia-22.04-py3.sif << EOF
source ~/miniconda3/bin/activate ~/miniconda3/envs/haoyang

source path.sh

python3 main3_ddp.py \
        --BATCH_SIZE 16 \
        --N_EPOCHS 300 \
        --save_dir /home/users/ntu/ccdshyzh/AcademiCodec/logs \
        --PATH  /home/users/ntu/ccdshyzh/AcademiCodec/saved_models \
        # --train_data_path /home3/hexin/speechbrain/recipes/VoxLingua107/lang_id/fleurs_train.json \
        # --valid_data_path /home3/hexin/speechbrain/recipes/VoxLingua107/lang_id/fleurs_valid.json \
        --train_data_path /home/users/ntu/ccdshyzh/datasets/LibriSpeech/train-clean-100/103/1240 \
        --valid_data_path /home/users/ntu/ccdshyzh/datasets/LibriSpeech/train-clean-100/103/1241 \
        --sr 16000 \
        --ratios 6 5 4 2 \
        --target_bandwidths 1 2 4 8 12